#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BUFFSCRIPT,
	CAMERAMOVESCRIPT,
	DIAGONALHEADSHOTSCRIPT,
	DIAGONALPISTOLSCRIPT,
	DOUBLEGUNHAWKSCRIPT,
	GUNHAWKEXPLODESCRIPT,
	HAMMERSCRIPT,
	HEADSHOTEFFECTSCRIPT,
	HEADSHOTSCRIPT,
	JACKSPIKESCRIPT,
	MACHKICKSCRIPT,
	MELTKNIGHTSCRIPT,
	MONSTERMOVESCRIPT,
	MUZZLESCRIPT,
	PISTOLSCRIPT,
	PLATFORMSCRIPT,
	PLAYERMOVESCRIPT,
	PLAYERSCRIPT,
	RANDOMSHOOTSCRIPT,
	RISINGSHOTSCRIPT,
	SERIAROOMGATESCRIPT,
	SERIASCRIPT,
	WINDMILLSCRIPT,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
