#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BBQSCRIPT,
	BOSSCURHPBARSCRIPT,
	BOSSCURHPFONTSCRIPT,
	BOSSHUDSCRIPT,
	BOSSMAXHPBARSCRIPT,
	BOSSNEXTHPBARSCRIPT,
	BUFFSCRIPT,
	CAMERAMOVESCRIPT,
	DIAGONALHEADSHOTSCRIPT,
	DIAGONALPISTOLSCRIPT,
	DIREZIESCRIPT,
	DIREZIEWINDSCRIPT,
	DOUBLEGUNHAWKSCRIPT,
	DUMMYSCRIPT,
	EFFECTSCRIPT,
	GATLINGGUNPISTOLSCRIPT,
	GATLINGGUNSCRIPT,
	GUNHAWKEXPLODESCRIPT,
	HAMMERSCRIPT,
	HEADSHOTEFFECTSCRIPT,
	HEADSHOTSCRIPT,
	HYUNGTEOPUNCHSCRIPT,
	HYUNGTEOSCRIPT,
	HYUNGTEOSTINGSCRIPT,
	IRONCAGESCRIPT,
	JACKSPIKESCRIPT,
	JURISSCRIPT,
	LOADINGSCRIPT,
	MACHKICKSCRIPT,
	MELTKNIGHTSCRIPT,
	MONSTERHPBARSCRIPT,
	MONSTERHPFONTSCRIPT,
	MONSTERHUDSCRIPT,
	MONSTERMOVESCRIPT,
	MONSTERNEXTHPBARSCRIPT,
	MONSTERWHITEBARSCRIPT,
	MUZZLESCRIPT,
	NAMEDMONSTERFACEHUDSCRIPT,
	NAMEDMONSTERHUDSCRIPT,
	PARTICLESCRIPT,
	PISTOLSCRIPT,
	PLATFORMSCRIPT,
	PLAYERFATIGUEHUDSCRIPT,
	PLAYERHUDBUTTONSCRIPT,
	PLAYERHUDSCRIPT,
	PLAYERMOVESCRIPT,
	PLAYERMPHUDSCRIPT,
	PLAYERSCRIPT,
	PLAYERUISCRIPT,
	PUNISHERPISTOLSCRIPT,
	PUNISHERSCRIPT,
	RANDOMSHOOTSCRIPT,
	RISINGSHOTSCRIPT,
	SERIAROOMGATESCRIPT,
	SERIASCRIPT,
	SKILLGROUNDSCRIPT,
	SKILLICONSCRIPT,
	UICAMERASCRIPT,
	WINDMILLSCRIPT,
	ESHPHONGATESCRIPT,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
