#pragma once

#include <vector>
#include <string>

enum STATE_TYPE
{
	DIREZIEAIRHITSTATE,
	DIREZIEATTACK01STATE,
	DIREZIEATTACK02STATE,
	DIREZIEATTACK03STATE,
	DIREZIEATTACK04STATE,
	DIREZIEATTACK05STATE,
	DIREZIEDEADSTATE,
	DIREZIEDOWNHITSTATE,
	DIREZIEFALLSTATE,
	DIREZIEFLYSTATE,
	DIREZIEHIDESTATE,
	DIREZIEHITSTATE,
	DIREZIEIDLESTATE,
	DIREZIESTIFFNESSSTATE,
	DIREZIETRACESTATE,
	DIREZIEWAKEUPSTATE,
	HYUNGTEOAIRHITSTATE,
	HYUNGTEOBUFFEATERSTATE,
	HYUNGTEODEADSTATE,
	HYUNGTEODOWNHITSTATE,
	HYUNGTEOEATSTATE,
	HYUNGTEOFALLSTATE,
	HYUNGTEOFLYSTATE,
	HYUNGTEOHITBBQSTATE,
	HYUNGTEOHITSTATE,
	HYUNGTEOIDLESTATE,
	HYUNGTEOLOOKSTATE,
	HYUNGTEOPUNCHSTATE,
	HYUNGTEORECOILSTATE,
	HYUNGTEOSTIFFNESSSTATE,
	HYUNGTEOSTINGSTATE,
	HYUNGTEOTRACESTATE,
	HYUNGTEOWAKEUPSTATE,
	JURISATTACKSTATE,
	JURISBACKATTACKSTATE,
	JURISDEADSTATE,
	JURISHIDESTATE,
	JURISHITSTATE,
	JURISIDLESTATE,
	JURISSTIFFNESSSTATE,
	JURISTRACESTATE,
	MELTKNIGHTATTACKSTATE,
	MELTKNIGHTDEADSTATE,
	MELTKNIGHTIDLESTATE,
	MELTKNIGHTSTANDBYSTATE,
	MELTKNIGHTTRACESTATE,
};

using namespace std;

class CState;

class CStateMgr
{
public:
	static void GetStateInfo(vector<wstring>& _vec);
	static CState * GetState(const wstring& _strStateName);
	static CState * GetState(UINT _iStateType);
	static const wchar_t * GetStateName(CState * _pState);
};
